import { StackNavigationProp } from "react-native-screens";

export type AuthStackParamList = {
  Confirmation: any;
  DriverDetails: any;
  TripConfirmation: any;
  RideIdentification: any;
  EndTrip: any;
  RideProgress: any;
  CarIdentification: any;
  AccountVerification: any;
  Settings: any;
  FAQs: any;
  IdDetails: any;
  IdVerification: any;
  WalletHome: any;
  PaymentSucessful: any;
  AddPaymentMethod: any;
  WalletHistory: any;
  AccountVerification: any;
  Settings: any;
  FAQs: any;
  IdDetails: any;
  IdVerification: any;
  WalletHome: any;
  PaymentSucessful: any;
  AddPaymentMethod: any;
  WalletHistory: any;
  Login: any;
  CreateAccount: any;
  Verification: any;
  Home: any;
  TripForm: any;
  RideSchedule: any;
  RideSelection: any;
  MapScreen: any;
  Payment: any;
  VehicleDetails: any;
  RidePreference: any;
  BackRowSeating: any;
  PriceSetting: any;
  ManageTrips: any;
  TripItinerary: any;
};
